<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-D78M4RB" name="testCases.TC1" tests="3" failures="0" timestamp="2020-12-23T01:42:39 IST" time="25.397" errors="1">
  <testcase name="sampleMethod3" time="12.535" classname="testCases.TC1"/>
  <system-out/>
  <testcase name="sampleMethod" time="12.846" classname="testCases.TC1"/>
  <system-out/>
  <testcase name="sampleMethod2" time="0.016" classname="testCases.TC1">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at reporter.ExtentReporter.startTest(ExtentReporter.java:39)
at masterWrapper.CaptainOfTheShip.startReporting(CaptainOfTheShip.java:151)
at testCases.TC1.sampleMethod2(TC1.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- sampleMethod2 -->
  <system-out/>
</testsuite> <!-- testCases.TC1 -->
